version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Starting build on `date`
      - mvn clean install dockerfile:build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)-$(date '+%Y%m%d%H%M%S')
      - echo LOCAL_TAG=$LOCAL_TAG
      - REMOTE_TAG=$REPO_URL:latest
      - echo REMOTE_TAG=$REMOTE_TAG
      - docker tag $LOCAL_TAG $REMOTE_TAG
      - docker push $REMOTE_TAG  
      - REMOTE_TAG=$REPO_URL:$VERSION
      - echo REMOTE_TAG=$REMOTE_TAG
      - docker tag $LOCAL_TAG $REMOTE_TAG
      - docker push $REMOTE_TAG          
      - printf '{"Parameters":{"DockerImage":"%s"}}' $REMOTE_TAG > fargateconfig.json
      - cat fargateconfig.json      

artifacts:
    files: 
      - imagedefinitions.json
      - fargateconfig.json

cache:
    paths:
     - '/root/.m2/**/*'
