AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  MasterUserPassword:
    Type: String
    NoEcho: true
  NetworkStack:
    Type: String

Resources:
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: db subnet group
      SubnetIds: !Split [ ",", "Fn::ImportValue": !Sub "${NetworkStack}-Subnets" ]

  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: db
      VPCSecurityGroups:
        - "Fn::ImportValue": !Sub "${NetworkStack}-DatabaseSG"
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      MasterUsername: masteruser
      MasterUserPassword: !Ref MasterUserPassword
    DeletionPolicy: Delete

Outputs:
  DBPort:
    Value: !GetAtt DB.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-DBPort"
  DBAddress:
    Value: !GetAtt DB.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-DBAddress"
